[workspace]
resolver = "2"
members = [
    "constructive_opt",
    "dace",
    "dace_tests",
    "dace_trace_gen",
    "lease_cache_sim",
    "ri",
    "clam_cache"
]

[profile.release]
debug = true
lto = true
