name: Sync Submodules

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: recursive  # Checkout submodules

      - name: Update Submodules
        run: |
          git submodule update --remote --merge
          git add .
          git commit -m "Update submodules to latest commits" || echo "No changes to commit"
          git push origin main || echo "No changes to push"
          
      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Push Changes
        if: success()
        run: git push origin main
